DEFAULT_VERBOSITY = 1
DEFAULT_LIMIT = 10
DEFAULT_DELAY = 3
DEFAULT_TIMEOUT = 3
DEFAULT_MAX_RETRIES = 3
DEFAULT_IP_ROTATOR_COUNTRIES = ["IT", "FR", "DE", "ES", "GB", "US"]

GOOGLE_SEARCH_ENGINE = 'google'
DUCKDUCKGO_SEARCH_ENGINE = 'duckduckgo'
SEARCH_ENGINES = [GOOGLE_SEARCH_ENGINE, DUCKDUCKGO_SEARCH_ENGINE]
DEFAULT_SEARCH_ENGINE = DUCKDUCKGO_SEARCH_ENGINE
